### ISSUE TITLE
Support for Redmine 4.x?

### ISSUE THREAD

**Issue by wrock** [Restream/redmine_my_page_queries#33]

**Comment by franrebo84** [comment]
Hi! do you have plans for 4.x?

Thanks for your work!

**Comment by MichaelTJWard** [comment]
I loved this plugin when using Redmine 2.x.  Was really hoping that it would be updated to support 4.x.

**Comment by martinerler** [comment]
We would also like to see if there is support for 4.x
Any ideas so far?

**Comment by shazada** [comment]
What are the issues for 4.x? Can someone state the error it's getting when running this plugin with 4.x

**Comment by martinerler** [comment]
Hi,

Here are the errors on running the migration...

```
redmine@ubuntu_test:~/redmine$  bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/opt/redmine/redmine-4.1.0/plugins/redmine_my_page_queries/init.rb:3:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:181:in `block in load'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:172:in `each'
/opt/redmine/redmine-4.1.0/lib/redmine/plugin.rb:172:in `load'
/opt/redmine/redmine-4.1.0/config/initializers/30-redmine.rb:20:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/opt/redmine/redmine-4.1.0/config/environment.rb:16:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/opt/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

**Comment by dtamajon** [comment]
Hi! It would be nice to have compatibility with Redmine 4.1.

I include full trace:

```
# bundle exec rake redmine:plugins NAME=redmine_my_page_queries RAILS_ENV=production --trace
** Invoke redmine:plugins (first_time)
** Execute redmine:plugins
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `to_prepare' for ActionDispatch::Callbacks:Class
Did you mean?  to_param
/var/www/clients/client1/web1/web/plugins/redmine_my_page_queries/init.rb:3:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/www/clients/client1/web1/web/lib/redmine/plugin.rb:181:in `block in load'
/var/www/clients/client1/web1/web/lib/redmine/plugin.rb:172:in `each'
/var/www/clients/client1/web1/web/lib/redmine/plugin.rb:172:in `load'
/var/www/clients/client1/web1/web/config/initializers/30-redmine.rb:20:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `block in load'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:285:in `load'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:663:in `block in load_config_initializer'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/notifications.rb:170:in `instrument'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:662:in `load_config_initializer'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `each'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:619:in `block in <class:Engine>'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `each'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
/var/www/clients/client1/web1/web/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:337:in `require_environment!'
/var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `each'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:241:in `invoke_prerequisites'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/var/www/clients/client1/web1/web/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `block in execute'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `each'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:281:in `execute'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.5.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment

```
